language:
  - cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  - sudo apt-get install gcc-5 g++-5

  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

  - sudo apt-get install libboost-all-dev
  - sudo rm /usr/bin/gcc
  - sudo ln -s /usr/bin/gcc-4.7 /usr/bin/gcc

script:
  - mkdir bin
  - cd bin
  - cmake ..
  - make
  - ./run_tests